version: '3'
services:  
  app:
    container_name: miniterm
    restart: always
    image: maven:3.6.0-slim
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - "127.0.0.1:55555:8080"
    command: mvn clean spring-boot:run
