version: "3"
services:
  java:
    container_name: miniterm
    restart: always
    image: openjdk:8u181-jdk-alpine3.8
    working_dir: /app/
    volumes:
      - ./:/app/
      - ~/.m2:/root/.m2
    ports:
      - "127.0.0.1:55555:8080"
    command: java -XX:+UseSerialGC -jar target/miniterm-1.jar